@startuml

class Library #LightGray{

}

class Users #LightPink{
UserName
Password
Role


}

class Cashier #LightPink{
CashierID

}

class Stocker #LightPink{
StockerID
}

class Admin #LightPink{
AdminID
}

class Book #LightBlue  {
Code
}

class BookDescription #LightBlue   {
Title
Genre
CurrntStock
PurchasedCount
}

class Transcation #LightCyan{
TransactionID
CashierID
BookCode
Date
BookList
}

class Purchase #LightCyan{
}

class Customer #LightGray{

}



Users "1" -- "1" Cashier #pink
Users "1" -- "*" Stocker #pink
Users "1" -- "1" Admin  #pink

Stocker "1" -- "*" Book #blue:"Updates-stock"
Admin "1" -- "*" Cashier #green : "Add-or-remove"
Admin "1" -- "*" Stocker #green: "Add-or-remove"
Cashier "1" -- "*" Transcation #orange: "Performs"
Stocker "*" -- "*" Book #blue :"view"
Admin "1" -- "*" Book #green: "view"
Cashier"1" -- "*" Book #orange: "view""
Book "*" -- "1" BookDescription #red: "Describes"
Cashier"*" -- "1" Library #orange: "Member-of"
Stocker"*" -- "1" Library #blue : "Member-of"
Customer"*" -- "1*" Cashier #orange: "Communicates-with "
Book"*" -- "1" Library#red: "Owned-by"
Transcation"1" -- "1" Purchase : "Type-of"


skinparam class {
FontName Times New Roman
FontSize 15
 }




@enduml