@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> System: Initialize remove user
System --> Admin: prompt for user details
Admin -> System: Inserts the user details
alt succesful request
System --> Admin: verirfies user deletion
else no such user exists
System --> Admin: no user exists
end
@enduml