@startuml
autonumber

Stocker -> System: viewBooks()
System -> BookList: isEmpty()
alt Books exist
BookList --> System: false
System -> BookList: viewBooks()
BookList --> System: list<Book> books
System --> Stocker: preview books list
Stocker -> System: selects book
System --> Stocker: shows book
Stocker -> System: selects delete
System -> BookList: deleteBook(Book book)
BookList -> Book !!: delete
BookList --> System: confirmation message
System --> Stocker: confirms deletion
else BookList is empty
BookList --> System: true
System --> Stocker: shows error message "No books exist"
end

@enduml
